version: 2
jobs:
  build:
    working_directory: ~/ionic-native/
    docker:
      - image: node:7
    branches:
      - only:
        - cci2
    steps:
      - checkout
      - restore_cache:
         key: ionic-site
      - run:
         name: Prepare ionic-site repo
         command: ./scripts/docs/prepare.sh
      - save_cache:
         key: ionic-site
         paths:
         - ~/ionic-site/
      - restore_cache:
         key: node-modules-{{ checksum "package.json" }}
      - run:
         name: Install node modules
         command: npm i
      - save_cache:
         key: node-modules-{{ checksum "package.json" }} # used cached node_modules if package.json didn't change
         paths:
         - ~/ionic-native/node_modules/
      - run:
          name: Run tslint
          command: npm run lint
      - run:
          name: Update docs
          command: ./scripts/docs/update_docs.sh
